name: BlobDesign
version: ${project.version}
main: us.mytheria.blobdesign.BlobDesign
api-version: 1.19
load: STARTUP
depend: [ BlobLib ]
commands:
  headpresetblock:
    description: HeadPresetBlock
    usage: /headpresetblock <key>
    aliases: [ hpb ]
  blockdisplay:
    description: BlockDisplay
    usage: /blockdisplay <add/remove/placer>
    aliases: [ bdisplay, bd ]
  itemdisplay:
    description: ItemDisplay
    usage: /itemdisplay <add/remove/placer>
    aliases: [ idisplay, id ]
  dilement:
    description: DisplayElementAsset
    aliases: [ displayelementasset ]
  displayspawner:
    description: DisplaySpawner
    usage: /displayspawner <block/item>
    aliases: [ dspawner, dsp, ds ]
  displayeditor:
    description: DisplayEditor UIs
    usage: /displayeditor <block/item> <radius>
    aliases: [ deditor ]
