name: BlobDesign
version: ${project.version}
main: io.github.anjoismysign.blobdesign.BlobDesign
api-version: 1.19
load: STARTUP
depend: [ BlobLib ]
commands:
  headpresetblock:
    description: HeadPresetBlock
    usage: /headpresetblock <key>
    aliases: [ hpb ]
  blockdisplay:
    description: BlockDisplay
    usage: /blockdisplay <add/remove/placer>
    aliases: [ bdisplay, bd ]
  itemdisplay:
    description: ItemDisplay
    usage: /itemdisplay <add/remove/placer>
    aliases: [ idisplay, id ]
  dilement:
    description: DisplayElementAsset
    aliases: [ displayelementasset ]
  displaysummoner:
    description: DisplaySummoner
    usage: /disu <item_display/block_display>
    aliases: [ dsummoner, disu ]
  displayspawner:
    description: DisplaySpawner
    usage: /disp <block/item>
    aliases: [ dspawner, disp ]
  displayeditor:
    description: DisplayEditor UIs
    usage: /dedit <block/item> <radius>
    aliases: [ deditor, dedit ]
